name: serviceorders
version: '3.8'

services:
  serviceorders-api:
    image: ${DOCKER_REGISTRY-}serviceorders-api
    container_name: ServiceOrders.Api
    build:
      context: .
      dockerfile: ServiceOrders.Api/Dockerfile
    ports:
      - "5001:443"

  serviceorders-db:
    image: postgres:17-alpine
    container_name: ServiceOrders.Db
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: serviceorder-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strong_password_123!